import { Play, Plus, Search, Sparkles, X } from 'lucide-react'
import { FormEvent, useState } from 'react'
import { Link } from 'react-router-dom'
import PageHeader from '../components/PageHeader'
import { api } from '../services/api'

export default function Discover(){
  const[entry,setEntry]=useState('');const[queries,setQueries]=useState(['phòng trọ + 3 giờ sáng']);const[sources,setSources]=useState(['demo']);const[sort,setSort]=useState('RECENT');const[minScore,setMinScore]=useState(0);const[busy,setBusy]=useState(false);const[result,setResult]=useState<{new_results:number;errors:string[]} | null>(null);const[error,setError]=useState('');const[language,setLanguage]=useState('');const[minLength,setMinLength]=useState(60);const[maxLength,setMaxLength]=useState(5000);const[hasReplies,setHasReplies]=useState('');const[hasMedia,setHasMedia]=useState('');const[since,setSince]=useState('');const[until,setUntil]=useState('')
  const add=()=>{const value=entry.trim();if(value&&!queries.includes(value))setQueries([...queries,value]);setEntry('')}
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');setResult(null);try{setResult(await api.post('/search',{queries,sources,search_type:sort,language:language||null,since:since?new Date(since).toISOString():null,until:until?new Date(until).toISOString():null,min_text_length:minLength,max_text_length:maxLength,has_replies:hasReplies===''?null:hasReplies==='yes',has_media:hasMedia===''?null:hasMedia==='yes',min_story_score:minScore,limit:25}))}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
  const presets=async()=>{setBusy(true);setError('');try{setResult(await api.post(`/search/presets?source=${sources[0]}&limit_queries=20`))}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
  const toggle=(s:string)=>setSources(sources.includes(s)?sources.filter(x=>x!==s):[...sources,s])
  return <><PageHeader eyebrow="Discover → Filter → Rank" title="Khám phá câu chuyện" description="Kết hợp từ khóa bằng dấu + để tạo nhóm AND. Mỗi nguồn thất bại độc lập và không làm gián đoạn nguồn khác."/>
    <form className="panel" onSubmit={submit}><div className="field full"><label>Cụm từ tìm kiếm</label><div className="query-builder"><input className="input" value={entry} onChange={e=>setEntry(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();add()}}} placeholder="Ví dụ: camera + bóng người"/><button type="button" className="btn secondary" onClick={add}><Plus size={16}/> Thêm</button></div><div className="query-chips">{queries.map(q=><span className="query-chip" key={q}>{q}<button type="button" onClick={()=>setQueries(queries.filter(x=>x!==q))}><X size={13}/></button></span>)}</div></div>
      <div className="form-grid" style={{marginTop:22}}><div className="field wide"><label>Nguồn</label><div className="checkbox-row">{['demo','threads','reddit'].map(s=><label key={s}><input type="checkbox" checked={sources.includes(s)} onChange={()=>toggle(s)}/>{s==='demo'?'Demo data':s[0].toUpperCase()+s.slice(1)}</label>)}</div></div><div className="field"><label>Sắp xếp nguồn</label><select className="select" value={sort} onChange={e=>setSort(e.target.value)}><option value="RECENT">Mới nhất</option><option value="TOP">Nổi bật</option></select></div><div className="field"><label>Ngôn ngữ</label><select className="select" value={language} onChange={e=>setLanguage(e.target.value)}><option value="">Tất cả</option><option value="vi">Tiếng Việt</option><option value="en">English</option></select></div><div className="field"><label>Từ ngày</label><input className="input" type="date" value={since} onChange={e=>setSince(e.target.value)}/></div><div className="field"><label>Đến ngày</label><input className="input" type="date" value={until} onChange={e=>setUntil(e.target.value)}/></div><div className="field"><label>Độ dài tối thiểu</label><input className="input" type="number" min="0" value={minLength} onChange={e=>setMinLength(Number(e.target.value))}/></div><div className="field"><label>Độ dài tối đa</label><input className="input" type="number" min="1" value={maxLength} onChange={e=>setMaxLength(Number(e.target.value))}/></div><div className="field"><label>Có phản hồi</label><select className="select" value={hasReplies} onChange={e=>setHasReplies(e.target.value)}><option value="">Bất kỳ</option><option value="yes">Có</option><option value="no">Không</option></select></div><div className="field"><label>Có media</label><select className="select" value={hasMedia} onChange={e=>setHasMedia(e.target.value)}><option value="">Bất kỳ</option><option value="yes">Có</option><option value="no">Không</option></select></div><div className="field"><label>Điểm tối thiểu: {minScore}</label><input type="range" min="0" max="90" value={minScore} onChange={e=>setMinScore(Number(e.target.value))}/></div></div>
      <div className="notice">Threads cần quyền <code>threads_keyword_search</code>. Nếu chưa có credential, hãy giữ Demo data để đánh giá toàn bộ luồng.</div>{error&&<div className="alert error">{error}</div>}{result&&<div className="alert success">Đã thêm {result.new_results} kết quả mới. {result.errors.length?`Có ${result.errors.length} nguồn báo lỗi.`:''} <Link to="/stories">Mở Kho truyện →</Link></div>}
      <div className="header-actions"><button className="btn primary" disabled={busy||!queries.length||!sources.length}><Search size={16}/>{busy?'Đang tìm…':'Tìm kiếm'}</button><button type="button" className="btn ghost" disabled={busy||!sources.length} onClick={presets}><Play size={16}/> Tìm tất cả preset</button><Link className="btn ghost" to="/keywords"><Sparkles size={16}/> Keyword Lab</Link></div>
    </form>
    <section className="panel" style={{marginTop:18}}><div className="panel-title"><h2>Gợi ý bắt đầu</h2></div><div className="query-chips">{['chuyện ma','bệnh viện + ca đêm','camera + bóng người','tiếng gõ cửa','người lạ ngoài cửa','Grab + nghĩa trang','creepy encounter'].map(q=><button className="query-chip" key={q} onClick={()=>!queries.includes(q)&&setQueries([...queries,q])}>{q}</button>)}</div></section>
  </>
}
