import { Download, Filter } from 'lucide-react'
import { useEffect, useState } from 'react'
import PageHeader from '../components/PageHeader'
import StoryCard from '../components/StoryCard'
import { Empty, ErrorBox, Loading } from '../components/States'
import { api } from '../services/api'
import type { Story } from '../types'

type Data={items:Story[];total:number;page:number;page_size:number;pages:number}
export default function Inbox(){const[data,setData]=useState<Data|null>(null);const[error,setError]=useState('');const[page,setPage]=useState(1);const[status,setStatus]=useState('');const[source,setSource]=useState('');const[sort,setSort]=useState('score');const[q,setQ]=useState('');const load=()=>{const p=new URLSearchParams({page:String(page),status,source,sort,q});api.get<Data>(`/stories?${p}`).then(setData).catch(e=>setError(e.message))};useEffect(load,[page,status,source,sort,q]);const action=async(a:string,s:Story)=>{if(a==='idea')await api.post(`/stories/${s.id}/idea`);else await api.patch(`/stories/${s.id}`,{status:a==='save'?'SAVED':'REJECTED'});load()};return <><PageHeader eyebrow="Review queue" title="Kho truyện" description="Lọc, đối chiếu nguồn và quyết định câu chuyện nào xứng đáng đi tiếp." actions={<><a className="btn ghost" href="/api/export/stories.json"><Download size={15}/> JSON</a><a className="btn ghost" href="/api/export/stories.csv"><Download size={15}/> CSV</a></>}/><div className="panel" style={{marginBottom:18}}><div className="form-grid"><div className="field wide"><label>Tìm trong kho</label><input className="input" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Tiêu đề hoặc nội dung…"/></div><div className="field"><label>Trạng thái</label><select className="select" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">Tất cả</option><option value="UNREVIEWED">Chưa duyệt</option><option value="SAVED">Đã lưu</option><option value="REJECTED">Đã loại</option><option value="DUPLICATE">Nghi trùng</option></select></div><div className="field"><label>Nguồn</label><select className="select" value={source} onChange={e=>setSource(e.target.value)}><option value="">Tất cả</option><option>demo</option><option>threads</option><option>reddit</option></select></div><div className="field"><label>Sắp xếp</label><select className="select" value={sort} onChange={e=>setSort(e.target.value)}><option value="score">Điểm cao nhất</option><option value="recent">Mới khám phá</option><option value="oldest">Cũ nhất</option></select></div><div className="field"><label>Kết quả</label><div><Filter size={14}/> {data?.total??0} câu chuyện</div></div></div></div>{error&&<ErrorBox message={error}/>} {!data?<Loading/>:data.items.length?<div className="story-list">{data.items.map(s=><StoryCard key={s.id} story={s} onAction={action}/>)}</div>:<Empty/>}<div className="pagination"><button className="btn ghost small" disabled={page<=1} onClick={()=>setPage(page-1)}>Trước</button><span>Trang {data?.page??1} / {data?.pages??1}</span><button className="btn ghost small" disabled={page>=(data?.pages??1)} onClick={()=>setPage(page+1)}>Sau</button></div></>}

