import { Plus, Search, Trash2 } from 'lucide-react'
import { FormEvent, useEffect, useMemo, useState } from 'react'
import PageHeader from '../components/PageHeader'
import { Empty, ErrorBox, Loading } from '../components/States'
import { api } from '../services/api'
import type { Keyword } from '../types'

export default function Keywords(){const[items,setItems]=useState<Keyword[]|null>(null);const[error,setError]=useState('');const[q,setQ]=useState('');const[phrase,setPhrase]=useState('');const[category,setCategory]=useState('Ma Việt Nam');const load=()=>api.get<Keyword[]>('/keywords').then(setItems).catch(e=>setError(e.message));useEffect(load,[]);const categories=useMemo(()=>[...new Set(items?.map(i=>i.category)||[])],[items]);const shown=(items||[]).filter(i=>`${i.phrase} ${i.category}`.toLowerCase().includes(q.toLowerCase()));const add=async(e:FormEvent)=>{e.preventDefault();await api.post('/keywords',{phrase,category,language:'vi',enabled:true});setPhrase('');load()};const toggle=async(i:Keyword)=>{await api.patch(`/keywords/${i.id}`,{enabled:!i.enabled});load()};const del=async(id:number)=>{if(confirm('Xóa từ khóa này?')){await api.delete(`/keywords/${id}`);load()}};return <><PageHeader eyebrow={`${items?.length||0}+ truy vấn được gieo sẵn`} title="Keyword Lab" description="Xây bộ từ khóa, nhóm chủ đề và theo dõi truy vấn nào tạo ra câu chuyện đáng lưu."/><div className="panel" style={{marginBottom:18}}><form className="form-grid" onSubmit={add}><div className="field wide"><label>Thêm cụm từ</label><input required className="input" value={phrase} onChange={e=>setPhrase(e.target.value)} placeholder="Ví dụ: hành lang bệnh viện lúc 2 giờ sáng"/></div><div className="field"><label>Nhóm</label><input className="input" list="categories" value={category} onChange={e=>setCategory(e.target.value)}/><datalist id="categories">{categories.map(c=><option value={c} key={c}/>)}</datalist></div><div className="field"><label>&nbsp;</label><button className="btn primary"><Plus size={15}/> Thêm từ khóa</button></div></form></div><div className="panel"><div className="field" style={{marginBottom:15}}><label>Tìm nhanh</label><div className="query-builder"><Search size={18}/><input className="input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Lọc theo từ hoặc nhóm…"/></div></div>{error&&<ErrorBox message={error}/>} {!items?<Loading/>:<div className="table-wrap"><table><thead><tr><th>Bật</th><th>Từ khóa</th><th>Nhóm</th><th>Ngôn ngữ</th><th>Lượt chạy</th><th>Tìm thấy</th><th>Tỷ lệ lưu</th><th>Điểm TB</th><th></th></tr></thead><tbody>{shown.map(i=><tr key={i.id}><td><input className="toggle" type="checkbox" checked={i.enabled} onChange={()=>toggle(i)}/></td><td><b>{i.phrase}</b></td><td>{i.category}</td><td>{i.language}</td><td>{i.queries_run}</td><td>{i.stories_found}</td><td>{i.saved_rate}%</td><td>{i.average_score}</td><td><button className="btn ghost small danger" onClick={()=>del(i.id)}><Trash2 size={13}/></button></td></tr>)}</tbody></table>{!shown.length&&<Empty/>}</div>}</div></>}

